"""Domain enumerations."""

from __future__ import annotations

from enum import Enum, auto


class PokemonType(Enum):
    COLORLESS = auto()
    GRASS = auto()
    FIRE = auto()
    WATER = auto()
    LIGHTNING = auto()
    PSYCHIC = auto()
    FIGHTING = auto()
    DARKNESS = auto()
    METAL = auto()
    DRAGON = auto()
    RAINBOW = auto()
    TEAM_ROCKET = auto()
    UNKNOWN = auto()


class CardType(Enum):
    POKEMON = auto()
    ITEM = auto()
    TOOL = auto()
    SUPPORTER = auto()
    STADIUM = auto()
    BASIC_ENERGY = auto()
    SPECIAL_ENERGY = auto()
    UNKNOWN = auto()


class Stage(Enum):
    BASIC = auto()
    STAGE_1 = auto()
    STAGE_2 = auto()
    OTHER = auto()


class ActionType(Enum):
    DECK_SELECTION = auto()
    MAIN = auto()
    PLAY = auto()
    ATTACH = auto()
    EVOLVE = auto()
    ABILITY = auto()
    DISCARD = auto()
    RETREAT = auto()
    ATTACK = auto()
    END_TURN = auto()
    SELECT_CARD = auto()
    SELECT_NUMBER = auto()
    SELECT_YES_NO = auto()
    SELECT_ENERGY = auto()
    SELECT_SPECIAL_CONDITION = auto()


class StatusCondition(Enum):
    POISONED = auto()
    BURNED = auto()
    ASLEEP = auto()
    PARALYZED = auto()
    CONFUSED = auto()


class Zone(Enum):
    DECK = auto()
    HAND = auto()
    DISCARD = auto()
    ACTIVE = auto()
    BENCH = auto()
    PRIZE = auto()
    STADIUM = auto()
    ENERGY = auto()
    TOOL = auto()
    PRE_EVOLUTION = auto()
    PLAYER = auto()
    LOOKING = auto()
    UNKNOWN = auto()


class PlayerSide(Enum):
    SELF = auto()
    OPPONENT = auto()
    UNKNOWN = auto()


class GamePhase(Enum):
    DECK_SELECTION = auto()
    SETUP = auto()
    TURN_START = auto()
    MAIN = auto()
    ATTACK = auto()
    RESOLUTION = auto()
    TURN_END = auto()
    FINISHED = auto()
    UNKNOWN = auto()


class SelectType(Enum):
    MAIN = auto()
    CARD = auto()
    ATTACHED_CARD = auto()
    CARD_OR_ATTACHED_CARD = auto()
    ENERGY = auto()
    SKILL = auto()
    ATTACK = auto()
    EVOLVE = auto()
    COUNT = auto()
    YES_NO = auto()
    SPECIAL_CONDITION = auto()
    UNKNOWN = auto()


class SelectContext(Enum):
    MAIN = auto()
    SETUP_ACTIVE_POKEMON = auto()
    SETUP_BENCH_POKEMON = auto()
    SWITCH = auto()
    TO_ACTIVE = auto()
    TO_BENCH = auto()
    TO_FIELD = auto()
    TO_HAND = auto()
    DISCARD = auto()
    TO_DECK = auto()
    TO_DECK_BOTTOM = auto()
    TO_PRIZE = auto()
    NOT_MOVE = auto()
    DAMAGE_COUNTER = auto()
    DAMAGE_COUNTER_ANY = auto()
    DAMAGE = auto()
    REMOVE_DAMAGE_COUNTER = auto()
    HEAL = auto()
    EVOLVES_FROM = auto()
    EVOLVES_TO = auto()
    DEVOLVE = auto()
    ATTACH_FROM = auto()
    ATTACH_TO = auto()
    DETACH_FROM = auto()
    LOOK = auto()
    EFFECT_TARGET = auto()
    DISCARD_ENERGY_CARD = auto()
    DISCARD_TOOL_CARD = auto()
    SWITCH_ENERGY_CARD = auto()
    DISCARD_CARD_OR_ATTACHED_CARD = auto()
    DISCARD_ENERGY = auto()
    TO_HAND_ENERGY = auto()
    TO_DECK_ENERGY = auto()
    SWITCH_ENERGY = auto()
    SKILL_ORDER = auto()
    ATTACK = auto()
    DISABLE_ATTACK = auto()
    EVOLVE = auto()
    DRAW_COUNT = auto()
    DAMAGE_COUNTER_COUNT = auto()
    REMOVE_DAMAGE_COUNTER_COUNT = auto()
    IS_FIRST = auto()
    MULLIGAN = auto()
    ACTIVATE = auto()
    FIRST_EFFECT = auto()
    MORE_DEVOLVE = auto()
    COIN_HEAD = auto()
    AFFECT_SPECIAL_CONDITION = auto()
    RECOVER_SPECIAL_CONDITION = auto()
    UNKNOWN = auto()


class OptionType(Enum):
    NUMBER = auto()
    YES = auto()
    NO = auto()
    CARD = auto()
    TOOL_CARD = auto()
    ENERGY_CARD = auto()
    ENERGY = auto()
    PLAY = auto()
    ATTACH = auto()
    EVOLVE = auto()
    ABILITY = auto()
    DISCARD = auto()
    RETREAT = auto()
    ATTACK = auto()
    END = auto()
    SKILL = auto()
    SPECIAL_CONDITION = auto()
    UNKNOWN = auto()


class LogType(Enum):
    SHUFFLE = auto()
    HAS_BASIC_POKEMON = auto()
    TURN_START = auto()
    TURN_END = auto()
    DRAW = auto()
    DRAW_REVERSE = auto()
    MOVE_CARD = auto()
    MOVE_CARD_REVERSE = auto()
    SWITCH = auto()
    CHANGE = auto()
    PLAY = auto()
    ATTACH = auto()
    EVOLVE = auto()
    DEVOLVE = auto()
    MOVE_ATTACHED = auto()
    ATTACK = auto()
    HP_CHANGE = auto()
    POISONED = auto()
    BURNED = auto()
    ASLEEP = auto()
    PARALYZED = auto()
    CONFUSED = auto()
    COIN = auto()
    RESULT = auto()
    UNKNOWN = auto()
